# Generated by Django 3.1.2 on 2020-11-21 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='native_languages',
            field=models.ManyToManyField(blank=True, related_name='tutor_native_language', to='tutors.Language'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euros'), ('RUB', 'Russian Rubles'), ('USD', 'US Dollars')], default='EUR', editable=False, max_length=3),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, related_name='language', to='tutors.Language')),
                ('native_language', models.ManyToManyField(blank=True, related_name='native_language', to='tutors.Language')),
                ('subjects', models.ManyToManyField(blank=True, to='tutors.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
