# Generated by Django 3.1.2 on 2020-11-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tutors', '0003_user_is_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='course',
            name='owner_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='owner_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_profile',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tutors.videoprofile'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='video_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.videoprofile'),
        ),
    ]
