# Generated by Django 3.1.2 on 2020-11-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
