# Generated by Django 3.1.2 on 2020-11-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_auto_20201124_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='video_profile',
        ),
        migrations.AddField(
            model_name='videoprofile',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutors.tutor'),
            preserve_default=False,
        ),
    ]
