# Generated by Django 3.1.2 on 2020-11-14 20:42

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='uploaded_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar cropping'),
        ),
    ]
