# Generated by Django 3.1.2 on 2020-11-29 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_auto_20201125_0616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOffer',
            new_name='JobRequest',
        ),
        migrations.RemoveField(
            model_name='videoprofile',
            name='parent',
        ),
        migrations.AddField(
            model_name='tutor',
            name='video_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutors.videoprofile'),
        ),
    ]
