# Generated by Django 3.1.2 on 2020-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0007_auto_20201129_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='video_profile',
        ),
        migrations.AddField(
            model_name='tutor',
            name='video_profile_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tutor',
            name='video_profile_url',
            field=models.URLField(blank=True),
        ),
    ]
