# Generated by Django 3.1.2 on 2020-12-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_auto_20201205_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='pdf_attachment',
            field=models.FileField(blank=True, upload_to='pdf_attachments'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='video_profile_file',
            field=models.FileField(blank=True, upload_to='video_profiles'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='video_profile_url',
            field=models.URLField(blank=True, verbose_name='Youtube Link (like https://www.youtube.com/embed/...xyz)'),
        ),
    ]
