# Generated by Django 3.1.2 on 2020-11-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_auto_20201114_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='avatar_file',
        ),
    ]
