# Generated by Django 3.1.2 on 2020-11-14 21:05

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0009_remove_tutor_avatar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='uploaded_images'),
        ),
    ]
