# Generated by Django 3.1.2 on 2020-12-05 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0009_auto_20201205_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='pdf_attachment',
            field=models.FileField(blank=True, upload_to='pdf_attachments', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
