# Generated by Django 3.1.2 on 2020-12-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_auto_20201205_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='is_public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
