# Generated by Django 3.1.2 on 2020-11-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0012_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='languages',
            field=models.ManyToManyField(to='tutors.Language'),
        ),
    ]
