---
- name: Deploy django app
  hosts: all
  gather_facts: false
  tasks:

  - name: pull changes
    become: yes
    become_user: ubuntu
    git:
      repo: git@github.com:pvaling/lingua.git
      dest: /home/ubuntu/lingua
      version: dev
      force: yes
      accept_hostkey: yes
      update: yes
      recursive: yes
      remote: origin

  - name: pip install
    become: yes
    become_user: ubuntu
    pip:
      requirements: /home/ubuntu/lingua/requirements.txt
