# Generated by Django 3.1.2 on 2020-11-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20201112_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar_file',
            field=models.FileField(blank=True, upload_to='files/avatars'),
        ),
    ]
