# Generated by Django 3.1.2 on 2020-11-12 22:29

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20201112_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar_file',
            field=models.FileField(blank=True, upload_to=teachers.models.user_directory_path),
        ),
    ]
